# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: app-svc
  annotations:
    kubernetes.io/elb.id: {{ .Values.sbercloud.elb.id}}
spec:
  selector:
    # selector that matches the pod
    app: app
  # type of service
  type: LoadBalancer
  ports:
  - protocol: TCP
    # port for exposing the service        
    port: {{ .Values.app.port }}
    # portfor exposing the pod             
    targetPort: {{ .Values.app.targetPort }}