# First, add the Service API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: app
  labels:
    # label your deployment
    app: app
spec:
  # The number of pods/replicas to run
  replicas: {{ .Values.pod.count }}       
  selector:
    matchLabels:
    # selector to match the pod
      app: app
  template:
    metadata:
      labels:
      # label your pod
        app: app
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: app-node
      # Add the local image name
        image: {{ .Values.app.image }}
        # never pull the image policy
        imagePullPolicy: Always
        ports:
        # port for running the container
        - containerPort: {{ .Values.app.targetPort }}