#cloud-config
package_update: true
packages:
  - git
  - curl
  - nano

runcmd:
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm -f kubectl
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  - chmod 700 get_helm.sh
  - sh ./get_helm.sh && rm -f ./get_helm.sh
  - yum install epel-release -y && yum install ansible -y