# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: app-svc
spec:
  selector:
    # selector that matches the pod
    app: app
  # type of service
  type: LoadBalancer
  ports:
  - protocol: TCP
    # port for exposing the service        
    port: 3001
    # portfor exposing the pod             
    targetPort: 3000
    # port for exposing the node       
    nodePort: 31110