---
- name: Deploy app to remote cloud container engine
  hosts: 127.0.0.1
  connection: local

  vars:
    dst: /root/.kube/

  tasks:
  - name: Create kube config
    copy: src={{ source_file }} dest={{ dst }} mode=0555

  - name: Connect to remote CCE
    shell: cd {{ dst }} && kubectl config use-context internal

  - name: Clone a github repository
    git:
     repo: https://github.com/CyberCutlet-11/main.git
     dest: /home/repo/
     clone: yes
     update: yes

  - name: Install helm chart
    kubernetes.core.helm:
      name: app
      chart_ref: /home/repo/helm/
      chart_version: 0.1.0
      release_namespace: "{{ namespace }}"
      - set_values:
        - value: sbercloud.elb.id={{ elb_id }}
          value_type: string